name: workflow.yml
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_USER: ${{ secrets.BOOKING_DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.BOOKING_DB_PASS }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.BOOKING_DB_ROOT_PASS }}
          MYSQL_DATABASE: Booking-service
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping -h localhost" --health-interval=10s --health-timeout=5s --health-retries=3

      customer-service:
        image: beatasp/booking-system-customer
        ports:
          - 8081:8081
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          CUSTOMER_DB_CLIENT_URL: http://customer-service:8081

      review-service:
        image: sleepingfores7s/booking-review
        ports:
          - 8083:8083
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          REVIEW_DB_CLIENT_URL: http://review-service:8083
    steps:
      #Check out code
      - name: checkout code
        uses: actions/checkout@v4
      # Run environment
      - name: set up java 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"
      # Run tests
      - name: Run tests
        env:
          BOOKING_DB_TEST_URL: jdbc:mysql://localhost:3307/Booking-service
          BOOKING_DB_USER: ${{ secrets.BOOKING_DB_USER }}
          BOOKING_DB_PASS: ${{ secrets.BOOKING_DB_PASS }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: mvn -B test
      # Build application
      - name: Build application
        env:
          BOOKING_DB_URL: jdbc:mysql://Booking-service:3306/Booking-service
          BOOKING_DB_USER: ${{ secrets.BOOKING_DB_USER }}
          BOOKING_DB_PASS: ${{ secrets.BOOKING_DB_PASS }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: mvn -B package -DskipTests
      - name: close
        if: always()
        run: docker compose down -v